platform :ios, '8.0'

target 'RealTimeAVideo' do

pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.6.2'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'YYModel', '~> 1.0.4'
pod 'IQKeyboardManager', '~> 4.0.7'
pod 'Masonry', '~> 1.0.2'
pod 'MagicalRecord', '~> 2.3.2'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'ReactiveCocoa', '2.5'

end



